name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  ci-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: |
        c++ -o flag_test flag_test.c -Wall -Wextra -Wpedantic -std=c++20
        cc -o flag_test flag_test.c -Wall -Wextra -Wpedantic -std=c99
    - name: run
      run: ./flag_test

  ci-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: build
      shell: cmd
      run: |
        clang++ -o flag_test.exe flag_test.c -Wall -Wextra -Wpedantic -std=c++20
        clang -o flag_test.exe flag_test.c -Wall -Wextra -Wpedantic -std=c99
    - name: run
      shell: cmd
      run: call flag_test.exe

  ci-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: |
        c++ -o flag_test flag_test.c -Wall -Wextra -Wpedantic -std=c++20
        cc -o flag_test flag_test.c -Wall -Wextra -Wpedantic -std=c99
    - name: run
      run: ./flag_test
