name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    strategy:
      matrix:
        os:
        - name: ubuntu-latest
          cc: cc
          cxx: c++
        - name: macos-latest
          cc: cc
          cxx: c++
        - name: windows-latest
          cc: clang
          cxx: clang++
        compiler:
        - lang: cc
          std: c90
        - lang: cxx
          std: c++20
        build:
        - flag_test
        - example
    runs-on: ${{ matrix.os.name }}
    steps:
    - uses: actions/checkout@v4
    - name: build
      shell: bash
      run: ${{ matrix.os.${{ matrix.compiler.lang }} }} -o ${{ matrix.build }} ${{ matrix.build }}.cpp -std=${{ matrix.compiler.std }} -Wall -Wextra -Wpedantic -g3 -fsanitize=address,undefined
    - name: run
      shell: bash
      run: ./${{ matrix.build }}
