name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
    - master

jobs:
  build:
    strategy:
      matrix:
        os:
        - name: ubuntu-latest
          compiler: cc
          std: c99
          sanitize: -g3 -fsanitize=address,undefined
        - name: ubuntu-latest
          compiler: c++
          std: c++20
          sanitize: -g3 -fsanitize=address,undefined
        - name: macos-latest
          compiler: cc
          std: c99
          sanitize: -g3 -fsanitize=address,undefined
        - name: macos-latest
          compiler: c++
          std: c++20
          sanitize: -g3 -fsanitize=address,undefined
        - name: windows-latest
          compiler: clang
          std: c99
        - name: windows-latest
          compiler: clang++
          std: c++20
        build:
        - flag_test
        - example

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: build
      shell: bash
      run: ${{ matrix.os.compiler }} -o ${{ matrix.build }} ${{ matrix.build }}.c -std=${{ matrix.os.std }} -Wall -Wextra -Wpedantic ${{ matrix.os.sanitize }}
    - name: run
      shell: bash
      run: ./${{ matrix.build }}
